-- If you want an SCP to be able to pick everything up again, remove their relevant line from the 'SCP' List.
local SCP = {
    ["SCP-999 'The Tickle Monster'"] = true,
    ["SCP-131-A 'Eyepods'"] = true,
    ["SCP-131-B 'Eyepods'"] = true,
    ["SCP-011-A 'Rats of Unusual Size'"] = true,
    ["SCP-011-B 'Rats of Unusual Size'"] = true,
    ["SCP-049 'The Plague Doctor'"] = true,
    ["SCP-066 'Erics Toy'"] = true,
    ["SCP-076-2 'Able'"] = true,
    ["SCP-082 'Fernand, the Cannibal'"] = true,
    ["SCP-106 'The Old Man'"] = true,
    ["SCP-542 'The Doctor'"] = true,
    ["SCP-682 'The Indestructible Lizard'"] = true,
    ["SCP-777 'Evada'"] = true,
    ["SCP-912 'Autonomous SWAT Armor'"] = true,
    ["SCP-939 'With Many Voices'"] = true,
    ["SCP-1048 'Builder Bear'"] = true,
    ["SCP-1048-A 'The Ear Bear'"] = true,
    ["SCP-1316 'Lucy the Kitten'"] = true,
    ["SCP-4451-27 'The Tiny Terrorsweeper'"] = true,
    ["SCP-939-63 'Princess'"] = true,
    ["SCP-1867 'A Gentleman'"] = true,
    ["SCP-2295 'Patchwork Bear'"] = true,
    ["SCP-4975 'Time's Up'"] = true,
    ["SCP-8974-A 'Greed'"] = true,
    ["SCP-8974-B 'Gluttony'"] = true,
    }
-- If you want to remove an item that an SCP can equip (removing most items here will break an SCP.) remove the relevant line, if you want to add one just follow the following format [weapon_name] = true,
local items = {
    ["weapon_ciga_cheap"] = true, 
    ["weapon_ciga_blat"] = true,
    ["weapon_ciga"] = true,
    ["food_coca_cola_can"] = true, 
    ["food_duff_beer_can"] = true, 
    ["food_fanta_can"] = true, 
    ["food_gg_water_can"] = true, 
    ["food_monster_can"] = true, 
    ["food_mountain_dew_can"] = true, 
    ["food_pepsi_can"] = true, 
    ["weapon_the_instrument"] = true, 
    ["gmod_camera"] = true, 
    ["slappers"] = true, 
    ["snowball_thrower_nodamage"] = true, 
    ["store_rubber-duck"] = true, 
    ["store_tablet"] = true, 
    ["store_suitcase"] = true,  
    ["store_clipboard"] = true, 
    ["weapon_scp999"] = true, 
    ["weapon_patchwork"] = true,
    ["new_weapon_049"] = true,
    ["new_weapon_4975"] = true,
    ["new_weapon_939"] = true,
    ["scp_035_swep"] = true,
    ["weapon_scp066"] = true,
    ["weapon_scp073"] = true,
    ["weapon_1048"] = true,
    ["gu_scp_106"] = true,
    ["mimic_swep"] = true,
    ["weapon_4975"] = true,
    ["fv_scp682"] = true,
    ["mvp_hands"] = true,
    ["scp_breacher"] = true,
    ["besc_breach"] = true,
    ["weapon_ablesword"] = true,
    ["weapon_fists"] = true,
    ["m9k_fists"] = true,
    ["cw_extrema_ratio_official"] = true,
    ["weapon_mad_eredin"] = true,
    ["weapon_stunstick"] = true,
    ["weapon_cuff_police"] = true,
    ["riot_shield"] = true,
    ["cloaking-infinite"] = true,
    ["weapon_empty_hands"] = true,
    ["weapon_cbroom"] = true,
    ["fas2_ifak"] = true,
    ["weapon_8974"] = true,
    ["weapon_physgun"] = true,
    ["gmod_tool"] = true,
    ["cw_gau_minigun"] = true, 
    ["new_weapon_049"] = true,
}


hook.Add( "PlayerCanPickupWeapon", "SCPandweapons", function( ply, weapon )
    if SCP[team.GetName( ply:Team() )] == true then
        if items[weapon:GetClass()] == true then
          return true
        else
          return false
        end
    end
end )